//! Generates `PoseidonT5.sol` from arkworks' *own* canonical-config constants, so the on-chain
//! Poseidon is byte-identical to the circuit's.
//!
//! Two hashes are emitted, both over the same t=5 permutation (8 full + 60 partial rounds,
//! alpha=5), matching the arkworks fixed-input sponge (capacity-first state, output = state[1]):
//!   * `hash4(a,b,c,d)` — the leaf hash and `netsAcc`/`withdrawalsAcc` fold (absorb 4).
//!   * `hash2(a,b)`     — the Merkle *node* hash used by the escape hatch's inclusion check,
//!                        matching the circuit's `h2` (absorb 2). Slots 3,4 stay zero.
//! Fixtures of (inputs -> output) computed by the circuit's native hasher pin both; the Foundry
//! test asserts them.

use ark_bn254::Fr;
use ledger_circuit::{canonical_config, PoseidonNative};

const BN254_FR_MODULUS: &str =
    "21888242871839275222246405745257275088548364400416034343698204186575808495617";

fn fr_dec(x: &Fr) -> String {
    format!("{x}")
}

/// Returns the generated `PoseidonT5.sol` source.
pub fn generate_solidity() -> String {
    let cfg = canonical_config::<Fr>();
    let t = cfg.rate + cfg.capacity; // 5
    let rounds = cfg.full_rounds + cfg.partial_rounds; // 68
    assert_eq!(t, 5, "generator assumes t=5");
    assert_eq!(cfg.ark.len(), rounds, "ark round count");
    assert_eq!(cfg.mds.len(), t, "mds rows");

    let mut ark_assigns = String::new();
    for (r, row) in cfg.ark.iter().enumerate() {
        for (j, v) in row.iter().enumerate() {
            ark_assigns.push_str(&format!("        ark[{}] = {};\n", r * t + j, fr_dec(v)));
        }
    }
    let mut mds_assigns = String::new();
    for (i, row) in cfg.mds.iter().enumerate() {
        for (j, v) in row.iter().enumerate() {
            mds_assigns.push_str(&format!("        mds[{}] = {};\n", i * t + j, fr_dec(v)));
        }
    }

    let full_half = cfg.full_rounds / 2; // 4
    let partial_end = full_half + cfg.partial_rounds; // 64

    format!(
        r#"// SPDX-License-Identifier: MIT
// GENERATED by `cargo run -p prover --bin gen_poseidon`. DO NOT EDIT BY HAND.
// Constants are arkworks' `poseidon_canonical_config` (BN254 Fr, t=5, 8 full + 60 partial
// rounds, alpha=5) — identical to the circuit's Poseidon. Pinned by poseidon_t5_fixture.json.
pragma solidity ^0.8.30;

library PoseidonT5 {{
    uint256 internal constant F = {modulus};
    uint256 internal constant ROUNDS = {rounds};
    uint256 internal constant FULL_HALF = {full_half};
    uint256 internal constant PARTIAL_END = {partial_end};

    /// Fixed 4-input Poseidon (leaf hash, netsAcc fold). Matches arkworks CRH over 4 inputs.
    function hash4(uint256 a, uint256 b, uint256 c, uint256 d) internal pure returns (uint256) {{
        uint256[{t}] memory s;
        s[1] = a % F;
        s[2] = b % F;
        s[3] = c % F;
        s[4] = d % F;
        return _permute(s)[1];
    }}

    /// 2-input Poseidon (Merkle node hash). Matches the circuit's `h2` (arkworks CRH over 2).
    function hash2(uint256 a, uint256 b) internal pure returns (uint256) {{
        uint256[{t}] memory s;
        s[1] = a % F;
        s[2] = b % F;
        return _permute(s)[1];
    }}

    /// netsAcc fold: acc' = Poseidon4(acc, payeeKey, tokenId, amount).
    function foldNet(uint256 acc, uint256 payeeKey, uint256 tokenId, uint256 amount)
        internal
        pure
        returns (uint256)
    {{
        return hash4(acc, payeeKey, tokenId, amount);
    }}

    function _permute(uint256[{t}] memory s) private pure returns (uint256[{t}] memory) {{
        uint256[{ark_len}] memory ark = _ark();
        uint256[{mds_len}] memory mds = _mds();
        for (uint256 r = 0; r < ROUNDS; r++) {{
            for (uint256 j = 0; j < {t}; j++) {{
                s[j] = addmod(s[j], ark[r * {t} + j], F);
            }}
            if (r < FULL_HALF || r >= PARTIAL_END) {{
                for (uint256 j = 0; j < {t}; j++) {{
                    s[j] = _pow5(s[j]);
                }}
            }} else {{
                s[0] = _pow5(s[0]);
            }}
            uint256[{t}] memory out;
            for (uint256 i = 0; i < {t}; i++) {{
                uint256 acc = 0;
                for (uint256 j = 0; j < {t}; j++) {{
                    acc = addmod(acc, mulmod(mds[i * {t} + j], s[j], F), F);
                }}
                out[i] = acc;
            }}
            s = out;
        }}
        return s;
    }}

    function _pow5(uint256 x) private pure returns (uint256) {{
        uint256 x2 = mulmod(x, x, F);
        uint256 x4 = mulmod(x2, x2, F);
        return mulmod(x4, x, F);
    }}

    function _ark() private pure returns (uint256[{ark_len}] memory ark) {{
{ark_assigns}    }}

    function _mds() private pure returns (uint256[{mds_len}] memory mds) {{
{mds_assigns}    }}
}}
"#,
        modulus = BN254_FR_MODULUS,
        rounds = rounds,
        full_half = full_half,
        partial_end = partial_end,
        t = t,
        ark_len = rounds * t,
        mds_len = t * t,
        ark_assigns = ark_assigns,
        mds_assigns = mds_assigns,
    )
}

/// Fixtures for `hash4` and `hash2`, computed by the circuit's native hasher.
pub fn generate_fixture() -> serde_json::Value {
    let native = PoseidonNative::<Fr>::new();
    let v4: Vec<[u64; 4]> = vec![[1, 2, 3, 4], [0, 0, 0, 0], [42, 7, 1, 99], [1_000_000, 2, 1, 500]];
    let hash4: Vec<serde_json::Value> = v4
        .iter()
        .map(|v| {
            let out = native.h4(Fr::from(v[0]), Fr::from(v[1]), Fr::from(v[2]), Fr::from(v[3]));
            serde_json::json!({
                "inputs": v.iter().map(|x| x.to_string()).collect::<Vec<_>>(),
                "output": crate::fr_to_hex(&out),
            })
        })
        .collect();
    let v2: Vec<[u64; 2]> = vec![[1, 2], [3, 4], [0, 0], [123456, 789]];
    let hash2: Vec<serde_json::Value> = v2
        .iter()
        .map(|v| {
            let out = native.h2(Fr::from(v[0]), Fr::from(v[1]));
            serde_json::json!({
                "inputs": v.iter().map(|x| x.to_string()).collect::<Vec<_>>(),
                "output": crate::fr_to_hex(&out),
            })
        })
        .collect();
    serde_json::json!({
        "hash4Count": hash4.len(),
        "hash2Count": hash2.len(),
        "hash4": hash4,
        "hash2": hash2,
    })
}
